version: '3.3'
services:
  nodegraph-provider:
    image: athenodon/nodegraph-provider:0.4.1
    container_name: nodegraph-provider
    restart: always
    environment:
      - NODEGRAPH_PROVIDER_PORT=9393
      - NODEGRAPH_PROVIDER_REDIS_HOST=redis
      - NODEGRAPH_PROVIDER_REDIS_PORT=6379
    ports:
      - '9393:9393'
    networks:
      - ng-net
    volumes:
      - ./ng_config.yaml:/app/config.yaml
    depends_on:
      - "redis"

  redis:
    image: redislabs/redismod
    container_name: redis
    restart: always
    networks:
      - ng-net
    ports:
      - '6379:6379'

  tta:
    image: athenodon/tempo_trace_aggregation:0.3.1
    depends_on:
      - "nodegraph-provider"
    networks:
      - ng-net
    volumes:
      - ./tta_config.yml:/app/config.yml

networks:
  ng-net:
    driver: bridge